language: "c"
before_script:
    - wget https://github.com/parrot/parrot/archive/RELEASE_5_3_0.zip
    - unzip RELEASE*
    - cd parrot-RELEASE*
    - pwd
    - perl Configure.pl --prefix="/tmp/installed_parrot" && make install
    - export PATH=/tmp/installed_parrot/bin/:$PATH
    - cd ..

before_install:
    - git submodule update --init --recursive
    - pg_config --version
    - perl --version|head -n2

script: "make && make check"

# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:

compiler:
  - clang
  - gcc
